//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_VolunteerState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Stores Volunteer specific data after Volunteer Applications are approved
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("csc_volunteer")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class csc_Volunteer : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string csc_10YearserviceMilestone = "csc_10yearservicemilestone";
			public const string csc_20YearserviceMilestone = "csc_20yearservicemilestone";
			public const string csc_5YearserviceMilestone = "csc_5yearservicemilestone";
			public const string csc_AboriginalPerson = "csc_aboriginalperson";
			public const string csc_AdminLocation = "csc_adminlocation";
			public const string csc_AgreeAgeOfMajority = "csc_agreeageofmajority";
			public const string csc_AgreeCanadianCitizen = "csc_agreecanadiancitizen";
			public const string csc_AgreeContactedWork = "csc_agreecontactedwork";
			public const string csc_AllowUpdate = "csc_allowupdate";
			public const string csc_ApplicationId = "csc_applicationid";
			public const string csc_Availability = "csc_availability";
			public const string csc_Birthday = "csc_birthday";
			public const string csc_BusinessTelephone = "csc_businesstelephone";
			public const string csc_BusinessTelephoneExt = "csc_businesstelephoneext";
			public const string csc_CACMembershipApprovalDate = "csc_cacmembershipapprovaldate";
			public const string csc_CACMembershipComment = "csc_cacmembershipcomment";
			public const string csc_CACMembershipExpiryDate = "csc_cacmembershipexpirydate";
			public const string csc_CACMembershipStatus = "csc_cacmembershipstatus";
			public const string csc_CanApplyCAC = "csc_canapplycac";
			public const string csc_CanApplyGeneral = "csc_canapplygeneral";
			public const string csc_CanApplyREAC = "csc_canapplyreac";
			public const string csc_Citizenship = "csc_citizenship";
			public const string csc_CSCVolunteerMembershipComment = "csc_cscvolunteermembershipcomment";
			public const string csc_CultureGroups = "csc_culturegroups";
			public const string csc_CultureOther = "csc_cultureother";
			public const string csc_Disabilities = "csc_disabilities";
			public const string csc_DisabilitiesOther = "csc_disabilitiesother";
			public const string csc_DisabilityComments = "csc_disabilitycomments";
			public const string csc_EmailVerifiedOn = "csc_emailverifiedon";
			public const string csc_FirstName = "csc_firstname";
			public const string csc_Gender = "csc_gender";
			public const string csc_GenderOther = "csc_genderother";
			public const string csc_GeneralMembershipApprovalDate = "csc_generalmembershipapprovaldate";
			public const string csc_GeneralMembershipStatus = "csc_generalmembershipstatus";
			public const string csc_hiidden_todays_date_Volunteerform = "csc_hiidden_todays_date_volunteerform";
			public const string csc_HomeAddressCity = "csc_homeaddresscity";
			public const string csc_HomeAddressCountry = "csc_homeaddresscountry";
			public const string csc_HomeAddressLine1 = "csc_homeaddressline1";
			public const string csc_HomeAddressLine2 = "csc_homeaddressline2";
			public const string csc_HomeAddressPostalCode = "csc_homeaddresspostalcode";
			public const string csc_HomeAddressProvinceOrState = "csc_homeaddressprovinceorstate";
			public const string csc_HomeTelephone = "csc_hometelephone";
			public const string csc_HRMSEmployeeID = "csc_hrmsemployeeid";
			public const string csc_IDBadgeExpiryDate = "csc_idbadgeexpirydate";
			public const string csc_IDBadgeNumber = "csc_idbadgenumber";
			public const string csc_IsCACVolunteer = "csc_iscacvolunteer";
			public const string csc_IsCSCEmployee = "csc_iscscemployee";
			public const string csc_IsCSCVolunteer = "csc_iscscvolunteer";
			public const string csc_IsREACVolunteer = "csc_isreacvolunteer";
			public const string csc_LastName = "csc_lastname";
			public const string csc_MaidenName = "csc_maidenname";
			public const string csc_MailingAddressCity = "csc_mailingaddresscity";
			public const string csc_MailingAddressCountry = "csc_mailingaddresscountry";
			public const string csc_MailingAddressLine1 = "csc_mailingaddressline1";
			public const string csc_MailingAddressLine2 = "csc_mailingaddressline2";
			public const string csc_MailingAddressPostalCode = "csc_mailingaddresspostalcode";
			public const string csc_MailingAddressProvinceOrState = "csc_mailingaddressprovinceorstate";
			public const string csc_MailingAddressSameAsHomeAddress = "csc_mailingaddresssameashomeaddress";
			public const string csc_MiddleName = "csc_middlename";
			public const string csc_MinorityGroups = "csc_minoritygroups";
			public const string csc_MinorityGroupsOther = "csc_minoritygroupsother";
			public const string csc_name = "csc_name";
			public const string csc_NationalVolunteersOrientationCompleted = "csc_nationalvolunteersorientationcompleted";
			public const string csc_OtherTelephone = "csc_othertelephone";
			public const string csc_OtherTelephoneExt = "csc_othertelephoneext";
			public const string csc_PermissiontouseSelfIdentification = "csc_permissiontouseselfidentification";
			public const string csc_PreferredLanguageofCommunication = "csc_preferredlanguageofcommunication";
			public const string csc_PreviousYearsOfService = "csc_previousyearsofservice";
			public const string csc_REACMembershipApprovalDate = "csc_reacmembershipapprovaldate";
			public const string csc_REACMembershipComment = "csc_reacmembershipcomment";
			public const string csc_REACMembershipExpiryDate = "csc_reacmembershipexpirydate";
			public const string csc_REACMembershipStatus = "csc_reacmembershipstatus";
			public const string csc_Received10YearPin = "csc_received10yearpin";
			public const string csc_Received20YearPin = "csc_received20yearpin";
			public const string csc_Received5YearPin = "csc_received5yearpin";
			public const string csc_ReferenceNumber = "csc_referencenumber";
			public const string csc_Region = "csc_region";
			public const string csc_SecondaryEmail = "csc_secondaryemail";
			public const string csc_SpeakEnglish = "csc_speakenglish";
			public const string csc_SpeakFrench = "csc_speakfrench";
			public const string csc_SumofAllInactiveDays = "csc_sumofallinactivedays";
			public const string csc_SumofAllInactiveDays_Date = "csc_sumofallinactivedays_date";
			public const string csc_SumofAllInactiveDays_State = "csc_sumofallinactivedays_state";
			public const string csc_TotalYearsofService = "csc_totalyearsofservice";
			public const string csc_VisibleMinorityComments = "csc_visibleminoritycomments";
			public const string csc_VolunteerActivationDate = "csc_volunteeractivationdate";
			public const string csc_VolunteerId = "csc_volunteerid";
			public const string Id = "csc_volunteerid";
			public const string csc_VolunteerStatusChangeDate = "csc_volunteerstatuschangedate";
			public const string csc_VolunteerStatusComment = "csc_volunteerstatuscomment";
			public const string csc_VolunteerSupervisor = "csc_volunteersupervisor";
			public const string EmailAddress = "emailaddress";
			public const string EntityImage = "entityimage";
			public const string EntityImage_Timestamp = "entityimage_timestamp";
			public const string EntityImage_URL = "entityimage_url";
			public const string EntityImageId = "entityimageid";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string processid = "processid";
			public const string stageid = "stageid";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string traversedpath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string csc_csc_country_csc_volunteer_HomeAddressCountry = "csc_csc_country_csc_volunteer_HomeAddressCountry";
			public const string csc_csc_country_csc_volunteer_MailingAddressCountry = "csc_csc_country_csc_volunteer_MailingAddressCountry";
			public const string csc_csc_location_csc_volunteer_AdminLocation = "csc_csc_location_csc_volunteer_AdminLocation";
			public const string csc_csc_nationality_csc_volunteer_Citizenship = "csc_csc_nationality_csc_volunteer_Citizenship";
			public const string csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState = "csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState";
			public const string csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState = "csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState";
			public const string csc_csc_region_csc_volunteer_Region = "csc_csc_region_csc_volunteer_Region";
			public const string csc_csc_volunteerapplication_csc_volunteer = "csc_csc_volunteerapplication_csc_volunteer";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public csc_Volunteer() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "csc_volunteer";
		
		public const string EntitySchemaName = "csc_Volunteer";
		
		public const string PrimaryIdAttribute = "csc_volunteerid";
		
		public const string PrimaryNameAttribute = "csc_name";
		
		public const int EntityTypeCode = 10078;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Has the volunteer reached his 10 year service milestone
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_10yearservicemilestone")]
		public System.Nullable<bool> csc_10YearserviceMilestone
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_10yearservicemilestone");
			}
		}
		
		/// <summary>
		/// Has the Volunteer reached his 20 years of service milestone
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_20yearservicemilestone")]
		public System.Nullable<bool> csc_20YearserviceMilestone
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_20yearservicemilestone");
			}
		}
		
		/// <summary>
		/// Has the volunteer reached his 5 year service milestone
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_5yearservicemilestone")]
		public System.Nullable<bool> csc_5YearserviceMilestone
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_5yearservicemilestone");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_aboriginalperson")]
		public Microsoft.Xrm.Sdk.OptionSetValueCollection csc_AboriginalPerson
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValueCollection>("csc_aboriginalperson");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_AboriginalPerson");
				this.SetAttributeValue("csc_aboriginalperson", value);
				this.OnPropertyChanged("csc_AboriginalPerson");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_adminlocation")]
		public Microsoft.Xrm.Sdk.EntityReference csc_AdminLocation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("csc_adminlocation");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_AdminLocation");
				this.SetAttributeValue("csc_adminlocation", value);
				this.OnPropertyChanged("csc_AdminLocation");
			}
		}
		
		/// <summary>
		/// Does the Volunteer Agree that they are at the age of Majority?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_agreeageofmajority")]
		public System.Nullable<bool> csc_AgreeAgeOfMajority
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_agreeageofmajority");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_AgreeAgeOfMajority");
				this.SetAttributeValue("csc_agreeageofmajority", value);
				this.OnPropertyChanged("csc_AgreeAgeOfMajority");
			}
		}
		
		/// <summary>
		/// Is the Volunteer a Canadian Citizen?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_agreecanadiancitizen")]
		public System.Nullable<bool> csc_AgreeCanadianCitizen
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_agreecanadiancitizen");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_AgreeCanadianCitizen");
				this.SetAttributeValue("csc_agreecanadiancitizen", value);
				this.OnPropertyChanged("csc_AgreeCanadianCitizen");
			}
		}
		
		/// <summary>
		/// Does the volunteer agree to be contacted at his place of work?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_agreecontactedwork")]
		public System.Nullable<bool> csc_AgreeContactedWork
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_agreecontactedwork");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_AgreeContactedWork");
				this.SetAttributeValue("csc_agreecontactedwork", value);
				this.OnPropertyChanged("csc_AgreeContactedWork");
			}
		}
		
		/// <summary>
		/// This field is for allowing the User to update the his/her volunteer information from the Portal.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_allowupdate")]
		public System.Nullable<bool> csc_AllowUpdate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_allowupdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_AllowUpdate");
				this.SetAttributeValue("csc_allowupdate", value);
				this.OnPropertyChanged("csc_AllowUpdate");
			}
		}
		
		/// <summary>
		/// Unique identifier for Volunteer Application associated with Volunteer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_applicationid")]
		public Microsoft.Xrm.Sdk.EntityReference csc_ApplicationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("csc_applicationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_ApplicationId");
				this.SetAttributeValue("csc_applicationid", value);
				this.OnPropertyChanged("csc_ApplicationId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_availability")]
		public string csc_Availability
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_availability");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Availability");
				this.SetAttributeValue("csc_availability", value);
				this.OnPropertyChanged("csc_Availability");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_birthday")]
		public System.Nullable<System.DateTime> csc_Birthday
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_birthday");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Birthday");
				this.SetAttributeValue("csc_birthday", value);
				this.OnPropertyChanged("csc_Birthday");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_businesstelephone")]
		public string csc_BusinessTelephone
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_businesstelephone");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_BusinessTelephone");
				this.SetAttributeValue("csc_businesstelephone", value);
				this.OnPropertyChanged("csc_BusinessTelephone");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_businesstelephoneext")]
		public string csc_BusinessTelephoneExt
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_businesstelephoneext");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_BusinessTelephoneExt");
				this.SetAttributeValue("csc_businesstelephoneext", value);
				this.OnPropertyChanged("csc_BusinessTelephoneExt");
			}
		}
		
		/// <summary>
		/// The date this individual was approved as a CAC.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_cacmembershipapprovaldate")]
		public System.Nullable<System.DateTime> csc_CACMembershipApprovalDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_cacmembershipapprovaldate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CACMembershipApprovalDate");
				this.SetAttributeValue("csc_cacmembershipapprovaldate", value);
				this.OnPropertyChanged("csc_CACMembershipApprovalDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_cacmembershipcomment")]
		public string csc_CACMembershipComment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_cacmembershipcomment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CACMembershipComment");
				this.SetAttributeValue("csc_cacmembershipcomment", value);
				this.OnPropertyChanged("csc_CACMembershipComment");
			}
		}
		
		/// <summary>
		/// The calculated date when the term as a CAC member expires. Three years after appointment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_cacmembershipexpirydate")]
		public System.Nullable<System.DateTime> csc_CACMembershipExpiryDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_cacmembershipexpirydate");
			}
		}
		
		/// <summary>
		/// A status field that identifies the "Status" of the Volunteers membership as a CAC Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_cacmembershipstatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue csc_CACMembershipStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("csc_cacmembershipstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CACMembershipStatus");
				this.SetAttributeValue("csc_cacmembershipstatus", value);
				this.OnPropertyChanged("csc_CACMembershipStatus");
			}
		}
		
		/// <summary>
		/// A flag indicating that a User from the Portal, or even in CRM can apply for a CAC application. This false if they are currently as CAC member, or they have an application being processed for this type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_canapplycac")]
		public System.Nullable<bool> csc_CanApplyCAC
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_canapplycac");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CanApplyCAC");
				this.SetAttributeValue("csc_canapplycac", value);
				this.OnPropertyChanged("csc_CanApplyCAC");
			}
		}
		
		/// <summary>
		/// A flag indicating that a User from the Portal, or even in CRM can apply for a GEN application. This false if they are currently as GEN member, or they have an application being processed for this type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_canapplygeneral")]
		public System.Nullable<bool> csc_CanApplyGeneral
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_canapplygeneral");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CanApplyGeneral");
				this.SetAttributeValue("csc_canapplygeneral", value);
				this.OnPropertyChanged("csc_CanApplyGeneral");
			}
		}
		
		/// <summary>
		/// A flag indicating that a User from the Portal, or even in CRM can apply for a REA application. This false if they are currently as REA member, or they have an application being processed for this type
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_canapplyreac")]
		public System.Nullable<bool> csc_CanApplyREAC
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_canapplyreac");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CanApplyREAC");
				this.SetAttributeValue("csc_canapplyreac", value);
				this.OnPropertyChanged("csc_CanApplyREAC");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_citizenship")]
		public Microsoft.Xrm.Sdk.EntityReference csc_Citizenship
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("csc_citizenship");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Citizenship");
				this.SetAttributeValue("csc_citizenship", value);
				this.OnPropertyChanged("csc_Citizenship");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_cscvolunteermembershipcomment")]
		public string csc_CSCVolunteerMembershipComment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_cscvolunteermembershipcomment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CSCVolunteerMembershipComment");
				this.SetAttributeValue("csc_cscvolunteermembershipcomment", value);
				this.OnPropertyChanged("csc_CSCVolunteerMembershipComment");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_culturegroups")]
		public Microsoft.Xrm.Sdk.OptionSetValueCollection csc_CultureGroups
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValueCollection>("csc_culturegroups");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CultureGroups");
				this.SetAttributeValue("csc_culturegroups", value);
				this.OnPropertyChanged("csc_CultureGroups");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_cultureother")]
		public string csc_CultureOther
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_cultureother");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_CultureOther");
				this.SetAttributeValue("csc_cultureother", value);
				this.OnPropertyChanged("csc_CultureOther");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_disabilities")]
		public Microsoft.Xrm.Sdk.OptionSetValueCollection csc_Disabilities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValueCollection>("csc_disabilities");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Disabilities");
				this.SetAttributeValue("csc_disabilities", value);
				this.OnPropertyChanged("csc_Disabilities");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_disabilitiesother")]
		public string csc_DisabilitiesOther
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_disabilitiesother");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_DisabilitiesOther");
				this.SetAttributeValue("csc_disabilitiesother", value);
				this.OnPropertyChanged("csc_DisabilitiesOther");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_disabilitycomments")]
		public string csc_DisabilityComments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_disabilitycomments");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_DisabilityComments");
				this.SetAttributeValue("csc_disabilitycomments", value);
				this.OnPropertyChanged("csc_DisabilityComments");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_emailverifiedon")]
		public System.Nullable<System.DateTime> csc_EmailVerifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_emailverifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_EmailVerifiedOn");
				this.SetAttributeValue("csc_emailverifiedon", value);
				this.OnPropertyChanged("csc_EmailVerifiedOn");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_firstname")]
		public string csc_FirstName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_firstname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_FirstName");
				this.SetAttributeValue("csc_firstname", value);
				this.OnPropertyChanged("csc_FirstName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_gender")]
		public Microsoft.Xrm.Sdk.OptionSetValue csc_Gender
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("csc_gender");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Gender");
				this.SetAttributeValue("csc_gender", value);
				this.OnPropertyChanged("csc_Gender");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_genderother")]
		public string csc_GenderOther
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_genderother");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_GenderOther");
				this.SetAttributeValue("csc_genderother", value);
				this.OnPropertyChanged("csc_GenderOther");
			}
		}
		
		/// <summary>
		/// The date this individual was approved as a CSC volunteer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_generalmembershipapprovaldate")]
		public System.Nullable<System.DateTime> csc_GeneralMembershipApprovalDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_generalmembershipapprovaldate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_GeneralMembershipApprovalDate");
				this.SetAttributeValue("csc_generalmembershipapprovaldate", value);
				this.OnPropertyChanged("csc_GeneralMembershipApprovalDate");
			}
		}
		
		/// <summary>
		/// A status field that identifies the "Status" of the Volunteers membership as a General Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_generalmembershipstatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue csc_GeneralMembershipStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("csc_generalmembershipstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_GeneralMembershipStatus");
				this.SetAttributeValue("csc_generalmembershipstatus", value);
				this.OnPropertyChanged("csc_GeneralMembershipStatus");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_hiidden_todays_date_volunteerform")]
		public System.Nullable<System.DateTime> csc_hiidden_todays_date_Volunteerform
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_hiidden_todays_date_volunteerform");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_homeaddresscity")]
		public string csc_HomeAddressCity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_homeaddresscity");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_HomeAddressCity");
				this.SetAttributeValue("csc_homeaddresscity", value);
				this.OnPropertyChanged("csc_HomeAddressCity");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_homeaddresscountry")]
		public Microsoft.Xrm.Sdk.EntityReference csc_HomeAddressCountry
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("csc_homeaddresscountry");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_HomeAddressCountry");
				this.SetAttributeValue("csc_homeaddresscountry", value);
				this.OnPropertyChanged("csc_HomeAddressCountry");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_homeaddressline1")]
		public string csc_HomeAddressLine1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_homeaddressline1");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_HomeAddressLine1");
				this.SetAttributeValue("csc_homeaddressline1", value);
				this.OnPropertyChanged("csc_HomeAddressLine1");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_homeaddressline2")]
		public string csc_HomeAddressLine2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_homeaddressline2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_HomeAddressLine2");
				this.SetAttributeValue("csc_homeaddressline2", value);
				this.OnPropertyChanged("csc_HomeAddressLine2");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_homeaddresspostalcode")]
		public string csc_HomeAddressPostalCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_homeaddresspostalcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_HomeAddressPostalCode");
				this.SetAttributeValue("csc_homeaddresspostalcode", value);
				this.OnPropertyChanged("csc_HomeAddressPostalCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_homeaddressprovinceorstate")]
		public Microsoft.Xrm.Sdk.EntityReference csc_HomeAddressProvinceOrState
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("csc_homeaddressprovinceorstate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_HomeAddressProvinceOrState");
				this.SetAttributeValue("csc_homeaddressprovinceorstate", value);
				this.OnPropertyChanged("csc_HomeAddressProvinceOrState");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_hometelephone")]
		public string csc_HomeTelephone
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_hometelephone");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_HomeTelephone");
				this.SetAttributeValue("csc_hometelephone", value);
				this.OnPropertyChanged("csc_HomeTelephone");
			}
		}
		
		/// <summary>
		/// Employee Identifier brought over in the HRMS Conversion
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_hrmsemployeeid")]
		public string csc_HRMSEmployeeID
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_hrmsemployeeid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_HRMSEmployeeID");
				this.SetAttributeValue("csc_hrmsemployeeid", value);
				this.OnPropertyChanged("csc_HRMSEmployeeID");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_idbadgeexpirydate")]
		public System.Nullable<System.DateTime> csc_IDBadgeExpiryDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_idbadgeexpirydate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_IDBadgeExpiryDate");
				this.SetAttributeValue("csc_idbadgeexpirydate", value);
				this.OnPropertyChanged("csc_IDBadgeExpiryDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_idbadgenumber")]
		public string csc_IDBadgeNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_idbadgenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_IDBadgeNumber");
				this.SetAttributeValue("csc_idbadgenumber", value);
				this.OnPropertyChanged("csc_IDBadgeNumber");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_iscacvolunteer")]
		public System.Nullable<bool> csc_IsCACVolunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_iscacvolunteer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_IsCACVolunteer");
				this.SetAttributeValue("csc_iscacvolunteer", value);
				this.OnPropertyChanged("csc_IsCACVolunteer");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_iscscemployee")]
		public System.Nullable<bool> csc_IsCSCEmployee
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_iscscemployee");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_IsCSCEmployee");
				this.SetAttributeValue("csc_iscscemployee", value);
				this.OnPropertyChanged("csc_IsCSCEmployee");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_iscscvolunteer")]
		public System.Nullable<bool> csc_IsCSCVolunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_iscscvolunteer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_IsCSCVolunteer");
				this.SetAttributeValue("csc_iscscvolunteer", value);
				this.OnPropertyChanged("csc_IsCSCVolunteer");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_isreacvolunteer")]
		public System.Nullable<bool> csc_IsREACVolunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_isreacvolunteer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_IsREACVolunteer");
				this.SetAttributeValue("csc_isreacvolunteer", value);
				this.OnPropertyChanged("csc_IsREACVolunteer");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_lastname")]
		public string csc_LastName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_lastname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_LastName");
				this.SetAttributeValue("csc_lastname", value);
				this.OnPropertyChanged("csc_LastName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_maidenname")]
		public string csc_MaidenName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_maidenname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MaidenName");
				this.SetAttributeValue("csc_maidenname", value);
				this.OnPropertyChanged("csc_MaidenName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddresscity")]
		public string csc_MailingAddressCity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_mailingaddresscity");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MailingAddressCity");
				this.SetAttributeValue("csc_mailingaddresscity", value);
				this.OnPropertyChanged("csc_MailingAddressCity");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddresscountry")]
		public Microsoft.Xrm.Sdk.EntityReference csc_MailingAddressCountry
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("csc_mailingaddresscountry");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MailingAddressCountry");
				this.SetAttributeValue("csc_mailingaddresscountry", value);
				this.OnPropertyChanged("csc_MailingAddressCountry");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddressline1")]
		public string csc_MailingAddressLine1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_mailingaddressline1");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MailingAddressLine1");
				this.SetAttributeValue("csc_mailingaddressline1", value);
				this.OnPropertyChanged("csc_MailingAddressLine1");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddressline2")]
		public string csc_MailingAddressLine2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_mailingaddressline2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MailingAddressLine2");
				this.SetAttributeValue("csc_mailingaddressline2", value);
				this.OnPropertyChanged("csc_MailingAddressLine2");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddresspostalcode")]
		public string csc_MailingAddressPostalCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_mailingaddresspostalcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MailingAddressPostalCode");
				this.SetAttributeValue("csc_mailingaddresspostalcode", value);
				this.OnPropertyChanged("csc_MailingAddressPostalCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddressprovinceorstate")]
		public Microsoft.Xrm.Sdk.EntityReference csc_MailingAddressProvinceOrState
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("csc_mailingaddressprovinceorstate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MailingAddressProvinceOrState");
				this.SetAttributeValue("csc_mailingaddressprovinceorstate", value);
				this.OnPropertyChanged("csc_MailingAddressProvinceOrState");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddresssameashomeaddress")]
		public System.Nullable<bool> csc_MailingAddressSameAsHomeAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_mailingaddresssameashomeaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MailingAddressSameAsHomeAddress");
				this.SetAttributeValue("csc_mailingaddresssameashomeaddress", value);
				this.OnPropertyChanged("csc_MailingAddressSameAsHomeAddress");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_middlename")]
		public string csc_MiddleName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_middlename");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MiddleName");
				this.SetAttributeValue("csc_middlename", value);
				this.OnPropertyChanged("csc_MiddleName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_minoritygroups")]
		public Microsoft.Xrm.Sdk.OptionSetValueCollection csc_MinorityGroups
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValueCollection>("csc_minoritygroups");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MinorityGroups");
				this.SetAttributeValue("csc_minoritygroups", value);
				this.OnPropertyChanged("csc_MinorityGroups");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_minoritygroupsother")]
		public string csc_MinorityGroupsOther
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_minoritygroupsother");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_MinorityGroupsOther");
				this.SetAttributeValue("csc_minoritygroupsother", value);
				this.OnPropertyChanged("csc_MinorityGroupsOther");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_name")]
		public string csc_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_name");
				this.SetAttributeValue("csc_name", value);
				this.OnPropertyChanged("csc_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_nationalvolunteersorientationcompleted")]
		public System.Nullable<bool> csc_NationalVolunteersOrientationCompleted
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_nationalvolunteersorientationcompleted");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_NationalVolunteersOrientationCompleted");
				this.SetAttributeValue("csc_nationalvolunteersorientationcompleted", value);
				this.OnPropertyChanged("csc_NationalVolunteersOrientationCompleted");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_othertelephone")]
		public string csc_OtherTelephone
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_othertelephone");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_OtherTelephone");
				this.SetAttributeValue("csc_othertelephone", value);
				this.OnPropertyChanged("csc_OtherTelephone");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_othertelephoneext")]
		public string csc_OtherTelephoneExt
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_othertelephoneext");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_OtherTelephoneExt");
				this.SetAttributeValue("csc_othertelephoneext", value);
				this.OnPropertyChanged("csc_OtherTelephoneExt");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_permissiontouseselfidentification")]
		public System.Nullable<bool> csc_PermissiontouseSelfIdentification
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_permissiontouseselfidentification");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_PermissiontouseSelfIdentification");
				this.SetAttributeValue("csc_permissiontouseselfidentification", value);
				this.OnPropertyChanged("csc_PermissiontouseSelfIdentification");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_preferredlanguageofcommunication")]
		public Microsoft.Xrm.Sdk.OptionSetValue csc_PreferredLanguageofCommunication
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("csc_preferredlanguageofcommunication");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_PreferredLanguageofCommunication");
				this.SetAttributeValue("csc_preferredlanguageofcommunication", value);
				this.OnPropertyChanged("csc_PreferredLanguageofCommunication");
			}
		}
		
		/// <summary>
		/// Represents the number of years this member has been active prior to moving from HRMS to the Engagement Portal
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_previousyearsofservice")]
		public System.Nullable<int> csc_PreviousYearsOfService
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("csc_previousyearsofservice");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_PreviousYearsOfService");
				this.SetAttributeValue("csc_previousyearsofservice", value);
				this.OnPropertyChanged("csc_PreviousYearsOfService");
			}
		}
		
		/// <summary>
		/// The date this individual was approved as a REAC.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_reacmembershipapprovaldate")]
		public System.Nullable<System.DateTime> csc_REACMembershipApprovalDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_reacmembershipapprovaldate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_REACMembershipApprovalDate");
				this.SetAttributeValue("csc_reacmembershipapprovaldate", value);
				this.OnPropertyChanged("csc_REACMembershipApprovalDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_reacmembershipcomment")]
		public string csc_REACMembershipComment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_reacmembershipcomment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_REACMembershipComment");
				this.SetAttributeValue("csc_reacmembershipcomment", value);
				this.OnPropertyChanged("csc_REACMembershipComment");
			}
		}
		
		/// <summary>
		/// The calculated date when the term as a REAC member expires.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_reacmembershipexpirydate")]
		public System.Nullable<System.DateTime> csc_REACMembershipExpiryDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_reacmembershipexpirydate");
			}
		}
		
		/// <summary>
		/// A status field that identifies the "Status" of the Volunteers membership as a REAC Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_reacmembershipstatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue csc_REACMembershipStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("csc_reacmembershipstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_REACMembershipStatus");
				this.SetAttributeValue("csc_reacmembershipstatus", value);
				this.OnPropertyChanged("csc_REACMembershipStatus");
			}
		}
		
		/// <summary>
		/// True if the user received the 10 year Recognition Pin. This value is updated automatically if an Awards or Recognition is created of type "10 Year service Recognition Pin"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_received10yearpin")]
		public System.Nullable<bool> csc_Received10YearPin
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_received10yearpin");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Received10YearPin");
				this.SetAttributeValue("csc_received10yearpin", value);
				this.OnPropertyChanged("csc_Received10YearPin");
			}
		}
		
		/// <summary>
		/// True if the user received the 20 year Recognition Pin. This value is updated automatically if an Awards or Recognition is created of type "20 Year service Recognition Pin"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_received20yearpin")]
		public System.Nullable<bool> csc_Received20YearPin
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_received20yearpin");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Received20YearPin");
				this.SetAttributeValue("csc_received20yearpin", value);
				this.OnPropertyChanged("csc_Received20YearPin");
			}
		}
		
		/// <summary>
		/// True if the user received the 5 year Recognition Pin. This value is updated automatically if an Awards or Recognition is created of type "5 Year service Recognition Pin"
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_received5yearpin")]
		public System.Nullable<bool> csc_Received5YearPin
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_received5yearpin");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Received5YearPin");
				this.SetAttributeValue("csc_received5yearpin", value);
				this.OnPropertyChanged("csc_Received5YearPin");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_referencenumber")]
		public string csc_ReferenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_referencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_ReferenceNumber");
				this.SetAttributeValue("csc_referencenumber", value);
				this.OnPropertyChanged("csc_ReferenceNumber");
			}
		}
		
		/// <summary>
		/// The Region that manages this volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_region")]
		public Microsoft.Xrm.Sdk.EntityReference csc_Region
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("csc_region");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_Region");
				this.SetAttributeValue("csc_region", value);
				this.OnPropertyChanged("csc_Region");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_secondaryemail")]
		public string csc_SecondaryEmail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_secondaryemail");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_SecondaryEmail");
				this.SetAttributeValue("csc_secondaryemail", value);
				this.OnPropertyChanged("csc_SecondaryEmail");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_speakenglish")]
		public System.Nullable<bool> csc_SpeakEnglish
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_speakenglish");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_SpeakEnglish");
				this.SetAttributeValue("csc_speakenglish", value);
				this.OnPropertyChanged("csc_SpeakEnglish");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_speakfrench")]
		public System.Nullable<bool> csc_SpeakFrench
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("csc_speakfrench");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_SpeakFrench");
				this.SetAttributeValue("csc_speakfrench", value);
				this.OnPropertyChanged("csc_SpeakFrench");
			}
		}
		
		/// <summary>
		/// This is a Rollup field, the sum is generated by finding all the records in the Volunteer History Status table that have the status of Inactive/Suspended/Partially Suspended/ Temporary Leave.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_sumofallinactivedays")]
		public System.Nullable<int> csc_SumofAllInactiveDays
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("csc_sumofallinactivedays");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field Sum of All Inactive Days.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_sumofallinactivedays_date")]
		public System.Nullable<System.DateTime> csc_SumofAllInactiveDays_Date
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_sumofallinactivedays_date");
			}
		}
		
		/// <summary>
		/// State of rollup field Sum of All Inactive Days.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_sumofallinactivedays_state")]
		public System.Nullable<int> csc_SumofAllInactiveDays_State
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("csc_sumofallinactivedays_state");
			}
		}
		
		/// <summary>
		/// Defines a Calculation for determining a volunteers total number of years of service.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_totalyearsofservice")]
		public System.Nullable<int> csc_TotalYearsofService
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("csc_totalyearsofservice");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_visibleminoritycomments")]
		public string csc_VisibleMinorityComments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_visibleminoritycomments");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_VisibleMinorityComments");
				this.SetAttributeValue("csc_visibleminoritycomments", value);
				this.OnPropertyChanged("csc_VisibleMinorityComments");
			}
		}
		
		/// <summary>
		/// The date in which the Applicant became a registered Volunteer. Either the approval date of the General, CAC or REAC application. Which ever came first.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_volunteeractivationdate")]
		public System.Nullable<System.DateTime> csc_VolunteerActivationDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_volunteeractivationdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_VolunteerActivationDate");
				this.SetAttributeValue("csc_volunteeractivationdate", value);
				this.OnPropertyChanged("csc_VolunteerActivationDate");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_volunteerid")]
		public System.Nullable<System.Guid> csc_VolunteerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("csc_volunteerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_VolunteerId");
				this.SetAttributeValue("csc_volunteerid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("csc_VolunteerId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_volunteerid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.csc_VolunteerId = value;
			}
		}
		
		/// <summary>
		/// The date for which the Volunteer Status Changed. Must be updated every time the status is changed. The initial date should be the date the Applicant became a volunteer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_volunteerstatuschangedate")]
		public System.Nullable<System.DateTime> csc_VolunteerStatusChangeDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("csc_volunteerstatuschangedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_VolunteerStatusChangeDate");
				this.SetAttributeValue("csc_volunteerstatuschangedate", value);
				this.OnPropertyChanged("csc_VolunteerStatusChangeDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_volunteerstatuscomment")]
		public string csc_VolunteerStatusComment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_volunteerstatuscomment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_VolunteerStatusComment");
				this.SetAttributeValue("csc_volunteerstatuscomment", value);
				this.OnPropertyChanged("csc_VolunteerStatusComment");
			}
		}
		
		/// <summary>
		/// A list of supervisors for this volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_volunteersupervisor")]
		public string csc_VolunteerSupervisor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("csc_volunteersupervisor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_VolunteerSupervisor");
				this.SetAttributeValue("csc_volunteersupervisor", value);
				this.OnPropertyChanged("csc_VolunteerSupervisor");
			}
		}
		
		/// <summary>
		/// The primary email address for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EmailAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EmailAddress");
				this.SetAttributeValue("emailaddress", value);
				this.OnPropertyChanged("EmailAddress");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EntityImage");
				this.SetAttributeValue("entityimage", value);
				this.OnPropertyChanged("EntityImage");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> processid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("processid");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("processid");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> stageid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("stageid");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("stageid");
			}
		}
		
		/// <summary>
		/// Status of the Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<CrmEarlyBound.csc_VolunteerState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((CrmEarlyBound.csc_VolunteerState)(System.Enum.ToObject(typeof(CrmEarlyBound.csc_VolunteerState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string traversedpath
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("traversedpath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("traversedpath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N csc_csc_volunteer_csc_portaluser_Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_volunteer_csc_portaluser_Volunteer")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.csc_PortalUser> csc_csc_volunteer_csc_portaluser_Volunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.csc_PortalUser>("csc_csc_volunteer_csc_portaluser_Volunteer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_volunteer_csc_portaluser_Volunteer");
				this.SetRelatedEntities<CrmEarlyBound.csc_PortalUser>("csc_csc_volunteer_csc_portaluser_Volunteer", null, value);
				this.OnPropertyChanged("csc_csc_volunteer_csc_portaluser_Volunteer");
			}
		}
		
		/// <summary>
		/// 1:N csc_csc_volunteer_csc_schedule_Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_volunteer_csc_schedule_Volunteer")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.csc_Schedule> csc_csc_volunteer_csc_schedule_Volunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.csc_Schedule>("csc_csc_volunteer_csc_schedule_Volunteer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_volunteer_csc_schedule_Volunteer");
				this.SetRelatedEntities<CrmEarlyBound.csc_Schedule>("csc_csc_volunteer_csc_schedule_Volunteer", null, value);
				this.OnPropertyChanged("csc_csc_volunteer_csc_schedule_Volunteer");
			}
		}
		
		/// <summary>
		/// 1:N csc_csc_volunteer_csc_volunteerapplication_CancelledBy
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_volunteer_csc_volunteerapplication_CancelledBy")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.csc_VolunteerApplication> csc_csc_volunteer_csc_volunteerapplication_CancelledBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.csc_VolunteerApplication>("csc_csc_volunteer_csc_volunteerapplication_CancelledBy", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_volunteer_csc_volunteerapplication_CancelledBy");
				this.SetRelatedEntities<CrmEarlyBound.csc_VolunteerApplication>("csc_csc_volunteer_csc_volunteerapplication_CancelledBy", null, value);
				this.OnPropertyChanged("csc_csc_volunteer_csc_volunteerapplication_CancelledBy");
			}
		}
		
		/// <summary>
		/// 1:N csc_csc_volunteer_csc_volunteerapplication_Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_volunteer_csc_volunteerapplication_Volunteer")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.csc_VolunteerApplication> csc_csc_volunteer_csc_volunteerapplication_Volunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.csc_VolunteerApplication>("csc_csc_volunteer_csc_volunteerapplication_Volunteer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_volunteer_csc_volunteerapplication_Volunteer");
				this.SetRelatedEntities<CrmEarlyBound.csc_VolunteerApplication>("csc_csc_volunteer_csc_volunteerapplication_Volunteer", null, value);
				this.OnPropertyChanged("csc_csc_volunteer_csc_volunteerapplication_Volunteer");
			}
		}
		
		/// <summary>
		/// 1:N csc_csc_volunteer_csc_volunteeremergencycontact_Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_volunteer_csc_volunteeremergencycontact_Volunteer")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.csc_VolunteerEmergencyContact> csc_csc_volunteer_csc_volunteeremergencycontact_Volunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.csc_VolunteerEmergencyContact>("csc_csc_volunteer_csc_volunteeremergencycontact_Volunteer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_volunteer_csc_volunteeremergencycontact_Volunteer");
				this.SetRelatedEntities<CrmEarlyBound.csc_VolunteerEmergencyContact>("csc_csc_volunteer_csc_volunteeremergencycontact_Volunteer", null, value);
				this.OnPropertyChanged("csc_csc_volunteer_csc_volunteeremergencycontact_Volunteer");
			}
		}
		
		/// <summary>
		/// 1:N csc_csc_volunteer_csc_volunteerlanguage_Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_volunteer_csc_volunteerlanguage_Volunteer")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.csc_VolunteerLanguage> csc_csc_volunteer_csc_volunteerlanguage_Volunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.csc_VolunteerLanguage>("csc_csc_volunteer_csc_volunteerlanguage_Volunteer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_volunteer_csc_volunteerlanguage_Volunteer");
				this.SetRelatedEntities<CrmEarlyBound.csc_VolunteerLanguage>("csc_csc_volunteer_csc_volunteerlanguage_Volunteer", null, value);
				this.OnPropertyChanged("csc_csc_volunteer_csc_volunteerlanguage_Volunteer");
			}
		}
		
		/// <summary>
		/// 1:N csc_csc_volunteer_csc_volunteerreference_Volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_volunteer_csc_volunteerreference_Volunteer")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.csc_VolunteerReference> csc_csc_volunteer_csc_volunteerreference_Volunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.csc_VolunteerReference>("csc_csc_volunteer_csc_volunteerreference_Volunteer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_volunteer_csc_volunteerreference_Volunteer");
				this.SetRelatedEntities<CrmEarlyBound.csc_VolunteerReference>("csc_csc_volunteer_csc_volunteerreference_Volunteer", null, value);
				this.OnPropertyChanged("csc_csc_volunteer_csc_volunteerreference_Volunteer");
			}
		}
		
		/// <summary>
		/// N:1 csc_csc_country_csc_volunteer_HomeAddressCountry
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_homeaddresscountry")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_country_csc_volunteer_HomeAddressCountry")]
		public CrmEarlyBound.csc_Country csc_csc_country_csc_volunteer_HomeAddressCountry
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.csc_Country>("csc_csc_country_csc_volunteer_HomeAddressCountry", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_country_csc_volunteer_HomeAddressCountry");
				this.SetRelatedEntity<CrmEarlyBound.csc_Country>("csc_csc_country_csc_volunteer_HomeAddressCountry", null, value);
				this.OnPropertyChanged("csc_csc_country_csc_volunteer_HomeAddressCountry");
			}
		}
		
		/// <summary>
		/// N:1 csc_csc_country_csc_volunteer_MailingAddressCountry
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddresscountry")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_country_csc_volunteer_MailingAddressCountry")]
		public CrmEarlyBound.csc_Country csc_csc_country_csc_volunteer_MailingAddressCountry
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.csc_Country>("csc_csc_country_csc_volunteer_MailingAddressCountry", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_country_csc_volunteer_MailingAddressCountry");
				this.SetRelatedEntity<CrmEarlyBound.csc_Country>("csc_csc_country_csc_volunteer_MailingAddressCountry", null, value);
				this.OnPropertyChanged("csc_csc_country_csc_volunteer_MailingAddressCountry");
			}
		}
		
		/// <summary>
		/// N:1 csc_csc_location_csc_volunteer_AdminLocation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_adminlocation")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_location_csc_volunteer_AdminLocation")]
		public CrmEarlyBound.csc_Location csc_csc_location_csc_volunteer_AdminLocation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.csc_Location>("csc_csc_location_csc_volunteer_AdminLocation", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_location_csc_volunteer_AdminLocation");
				this.SetRelatedEntity<CrmEarlyBound.csc_Location>("csc_csc_location_csc_volunteer_AdminLocation", null, value);
				this.OnPropertyChanged("csc_csc_location_csc_volunteer_AdminLocation");
			}
		}
		
		/// <summary>
		/// N:1 csc_csc_nationality_csc_volunteer_Citizenship
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_citizenship")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_nationality_csc_volunteer_Citizenship")]
		public CrmEarlyBound.csc_Nationality csc_csc_nationality_csc_volunteer_Citizenship
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.csc_Nationality>("csc_csc_nationality_csc_volunteer_Citizenship", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_nationality_csc_volunteer_Citizenship");
				this.SetRelatedEntity<CrmEarlyBound.csc_Nationality>("csc_csc_nationality_csc_volunteer_Citizenship", null, value);
				this.OnPropertyChanged("csc_csc_nationality_csc_volunteer_Citizenship");
			}
		}
		
		/// <summary>
		/// N:1 csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_homeaddressprovinceorstate")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState")]
		public CrmEarlyBound.csc_ProvinceOrState csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.csc_ProvinceOrState>("csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState");
				this.SetRelatedEntity<CrmEarlyBound.csc_ProvinceOrState>("csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState", null, value);
				this.OnPropertyChanged("csc_csc_provinceorstate_csc_volunteer_HomeAddressProvinceOrState");
			}
		}
		
		/// <summary>
		/// N:1 csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_mailingaddressprovinceorstate")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState")]
		public CrmEarlyBound.csc_ProvinceOrState csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.csc_ProvinceOrState>("csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState");
				this.SetRelatedEntity<CrmEarlyBound.csc_ProvinceOrState>("csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState", null, value);
				this.OnPropertyChanged("csc_csc_provinceorstate_csc_volunteer_MailingAddressProvinceOrState");
			}
		}
		
		/// <summary>
		/// N:1 csc_csc_region_csc_volunteer_Region
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_region")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_region_csc_volunteer_Region")]
		public CrmEarlyBound.csc_Region csc_csc_region_csc_volunteer_Region
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.csc_Region>("csc_csc_region_csc_volunteer_Region", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_region_csc_volunteer_Region");
				this.SetRelatedEntity<CrmEarlyBound.csc_Region>("csc_csc_region_csc_volunteer_Region", null, value);
				this.OnPropertyChanged("csc_csc_region_csc_volunteer_Region");
			}
		}
		
		/// <summary>
		/// N:1 csc_csc_volunteerapplication_csc_volunteer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_applicationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("csc_csc_volunteerapplication_csc_volunteer")]
		public CrmEarlyBound.csc_VolunteerApplication csc_csc_volunteerapplication_csc_volunteer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.csc_VolunteerApplication>("csc_csc_volunteerapplication_csc_volunteer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("csc_csc_volunteerapplication_csc_volunteer");
				this.SetRelatedEntity<CrmEarlyBound.csc_VolunteerApplication>("csc_csc_volunteerapplication_csc_volunteer", null, value);
				this.OnPropertyChanged("csc_csc_volunteerapplication_csc_volunteer");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public csc_Volunteer(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["csc_volunteerid"] = base.Id;
                        break;
                    case "csc_volunteerid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_aboriginalperson")]
		public virtual System.Collections.Generic.IEnumerable<csc_AboriginalPerson> csc_AboriginalPersonEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<csc_AboriginalPerson>(this, "csc_aboriginalperson");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_AboriginalPerson = EntityOptionSetEnum.GetMultiEnum(this, "csc_aboriginalperson", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_cacmembershipstatus")]
		public virtual csc_VolunteerMembershipStatus? csc_CACMembershipStatusEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((csc_VolunteerMembershipStatus?)(EntityOptionSetEnum.GetEnum(this, "csc_cacmembershipstatus")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_CACMembershipStatus = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_culturegroups")]
		public virtual System.Collections.Generic.IEnumerable<csc_CultureGroups> csc_CultureGroupsEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<csc_CultureGroups>(this, "csc_culturegroups");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_CultureGroups = EntityOptionSetEnum.GetMultiEnum(this, "csc_culturegroups", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_disabilities")]
		public virtual System.Collections.Generic.IEnumerable<csc_Disabilities> csc_DisabilitiesEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<csc_Disabilities>(this, "csc_disabilities");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_Disabilities = EntityOptionSetEnum.GetMultiEnum(this, "csc_disabilities", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_gender")]
		public virtual csc_Sex? csc_GenderEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((csc_Sex?)(EntityOptionSetEnum.GetEnum(this, "csc_gender")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_Gender = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_generalmembershipstatus")]
		public virtual csc_VolunteerMembershipStatus? csc_GeneralMembershipStatusEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((csc_VolunteerMembershipStatus?)(EntityOptionSetEnum.GetEnum(this, "csc_generalmembershipstatus")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_GeneralMembershipStatus = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_minoritygroups")]
		public virtual System.Collections.Generic.IEnumerable<csc_CultureGroups> csc_MinorityGroupsEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<csc_CultureGroups>(this, "csc_minoritygroups");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_MinorityGroups = EntityOptionSetEnum.GetMultiEnum(this, "csc_minoritygroups", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_preferredlanguageofcommunication")]
		public virtual csc_Volunteer_csc_PreferredLanguageofCommunication? csc_PreferredLanguageofCommunicationEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((csc_Volunteer_csc_PreferredLanguageofCommunication?)(EntityOptionSetEnum.GetEnum(this, "csc_preferredlanguageofcommunication")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_PreferredLanguageofCommunication = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("csc_reacmembershipstatus")]
		public virtual csc_VolunteerMembershipStatus? csc_REACMembershipStatusEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((csc_VolunteerMembershipStatus?)(EntityOptionSetEnum.GetEnum(this, "csc_reacmembershipstatus")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				csc_REACMembershipStatus = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual csc_Volunteer_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((csc_Volunteer_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}