//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\ricardosaracino\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://dev-csc-scc.api.crm3.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"CrmEarlyBound" /out:"C:\Users\ricardosaracino\Projects\TodoNET\TodoNET\Entities\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_AboriginalPerson
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndigenousPerson = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inuit = 862430003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mtis = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NorthAmericanIndianFirstNationMember = 862430001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_appovedordenied
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Denied = 862430001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_ContactMethodTypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 862430001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_CultureGroups
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Black = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Chinese = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Filipino = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Japanese = 862430003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Korean = 862430004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonWhiteLatinAmerican = 862430008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonWhiteWestAsianNorthAfricanorArab = 862430007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PersonsofMixedOrigin = 862430009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SouthAsianEastIndian = 862430005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SoutheastAsian = 862430006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_Disabilities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BlindorVisuallyImpaired = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CoordinationorDexterity = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeaforHardofHearing = 862430003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mobility = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NANotdisable = 862430008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NCDidnotcategorize = 862430007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NRNoResponse = 862430006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Otherdisability = 862430005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpeechImpairment = 862430004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_EmergencyContactRelationship
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdultChild = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aunt = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Brother = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Daughter = 862430003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DomesticPartnerAdult = 862430014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DomesticPartnerDaughter = 862430015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DomesticPartnerSon = 862430018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Employee = 862430004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Estate = 862430026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExSpouse = 862430028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Father = 862430005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FatherinLaw = 862430006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FosterDaughter = 862430030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FosterSon = 862430031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Friend = 862430007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Grandchild = 862430008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Grandfather = 862430009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Grandmother = 862430010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mother = 862430011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MotherinLaw = 862430012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Neighbor = 862430013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nephew = 862430016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Niece = 862430017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 862430019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OtherRelative = 862430020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecognizedChild = 862430029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Roommate = 862430021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Self = 862430024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sister = 862430023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Son = 862430022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Spouse = 862430025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Uncle = 862430027,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_GeneralActivityTypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AboriginalOffenders = 862430007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Accompaniment = 862430012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrative = 862430008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ArtsandCrafts = 862430003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CounsellingMentoring = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CulturalEthnic = 862430011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Education = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeisureActivities = 862430006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonSecurityEscort = 862430004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReligiousPrograms = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RestorativeJustice = 862430005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SelfHelp = 862430010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WomenOffenders = 862430009,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_PhoneType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Business = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Campus = 862430006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cellular = 862430005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dormitory = 862430007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FAX = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Home = 862430004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Main = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 862430011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pager1 = 862430008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pager2 = 862430009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Telex = 862430010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Work = 862430003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_PortalUser_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_ProvinceOrState_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_referencetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both_Other = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Personal = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Professional = 862430001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_Sex
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Female = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Male = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 862430002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_Volunteer_csc_PreferredLanguageofCommunication
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		English = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		French = 862430001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_Volunteer_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deceased = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnLeave = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resigned = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Terminated = 862430003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_VolunteerApplication_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 862430007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Denied = 862430005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 862430011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 862430012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Submitted = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Withdrawn = 862430003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_VolunteerApplicationType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CitizensAdvisoryCommittee_CACMembership = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CSCVolunteer = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RegionalEthnoCulturalAdvisoryCommitee_REACMembership = 862430001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_VolunteerEmergencyContact_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_VolunteerLanguage_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_VolunteerMembershipStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 862430000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationinProgress = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationRejected = 862430006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationWithdrawn = 862430008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deceased = 862430002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 862430004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NA = 862430003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnLeave = 862430009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resigned = 862430005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Suspended = 862430007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Terminated = 862430010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnderReview = 862430011,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_VolunteerReference_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum csc_YesNo
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 862430001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 862430000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum cmss_request_cmss_SoleSourceJustifications
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Theneedisoneofpressingemergencyinwhichdelaywouldbeinjurioustothepublicinterest = 551160000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheestimatedexpendituresdoesnotexceedCurrencySymbol_25K_allapplicabletaxesincluded = 551160001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thenatureoftheworkissuchthatitwouldnotbeinthepublicinteresttosolicitbids = 551160002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Onlyoneindividualorsupplieriscapableofperformingthecontract_answerstothesevenTreasuryBoardquestionsforsolesourcemustbeprovided = 551160003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Additionalsolesourcejustificationpleasespecify = 551160004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum cmss_cattcontract_cmss_SoleSourceJustifications
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Theneedisoneofpressingemergencyinwhichdelaywouldbeinjurioustothepublicinterest = 551160000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheestimatedexpendituresdoesnotexceedCurrencySymbol_25K_allapplicabletaxesincluded = 551160001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thenatureoftheworkissuchthatitwouldnotbeinthepublicinteresttosolicitbids = 551160002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Onlyoneindividualorsupplieriscapableofperformingthecontract_answerstothesevenTreasuryBoardquestionsforsolesourcemustbeprovided = 551160003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Additionalsolesourcejustificationpleasespecify = 551160004,
	}
}
